###############################################################################
# BANDIT CONFIGURATIONS
###############################################################################

#
# Reference:
# https://bandit.readthedocs.io/en/latest/config.html
#

# Excluded path globs
# exclude_dirs:

# Allow the use of assert in tests
assert_used:
  skips:
    - test_*.py

###############################################################################
