# .readthedocs.yaml
# NOTE - Currently set to OFF until issues with RTD integration with MkDocs is resolved.
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Build documentation in the docs/ directory with mkdocs
mkdocs:
  configuration: mkdocs.yml

# We recommend specifying your dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
# Removed April 2025
# python:
#   install:
#     - requirements: docs/requirements.txt
