site_name: AWS RDK Documentation
theme:
  name: material
  palette:
    scheme: default
    primary: orange
plugins:
  - search
  # TODO: Enable this if/when docstrings are expanded in the core rdk module.
  # - mkdocstrings:
  #     handlers:
  #       python:
  #         paths: [rdk]
markdown_extensions:
  - markdown_include.include:
      base_path: .
docs_dir: docs
