import yaml
import boto3

with open("rdk/rdklib_versions.yaml", "r") as f:
    # read the file
    regions = yaml.safe_load(f)

version_dict = {"rdklib_layer_versions": {}}
for region in regions["rdklib_layer_versions"]:
    lambda_client = boto3.client(
        "lambda",
        config=boto3.session.Config(region_name=region),
    )
    latest_version = lambda_client.list_layer_versions(LayerName="rdklib-layer", MaxItems=1)["LayerVersions"][0][
        "Version"
    ]
    version_dict["rdklib_layer_versions"][region] = latest_version

with open("rdk/rdklib_versions.yaml", "w") as f:
    f.write(
        """
# This file should be updated to contain the latest stable Lambda layer from the rdklib SAM application.
# Layers are published to each region, which is why some have more versions than others.
# This file was automatically generated by update_rdklib_versions.py; check for accuracy before deploying.
"""
    )
    f.write(yaml.dump(version_dict))
