#  Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with
#  the License. A copy of the License is located at
#      http://aws.amazon.com/apache2.0/
#  or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
#  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and
#  limitations under the License.

AWSTemplateFormatVersion: 2010-09-09

Parameters:
   CloudWatchEventIAMRole:
     Type: String
     Description: The IAM role that grants CloudWatchEvent access to create OpsItems
     Default: opscenter-role

Resources:
  S3BucketServerSideEncryptionEnabled:
    Type: AWS::Config::ConfigRule
    Properties:
      Scope:
        ComplianceResourceTypes:
          - "AWS::S3::Bucket"
      Source:
        Owner: AWS
        SourceIdentifier: "S3_BUCKET_SERVER_SIDE_ENCRYPTION_ENABLED"

  OpsItemGenForS3BucketServerSideEncryptionEnabled:
     Type: 'AWS::Events::Rule'
     Properties:
       Description: "CloudWatch Rule which creates Ops Items for CloudTrail Compliance Events"
       EventPattern:
         source:
           - aws.config
         detail-type:
           - 'Config Rules Compliance Change'
         detail:
           configRuleName:
             - !Ref S3BucketServerSideEncryptionEnabled
           newEvaluationResult:
             complianceType:
               - NON_COMPLIANT
       State: "ENABLED"
       Targets:
         - Arn: !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:opsitem
           Id: SSM-OpsItem
           RoleArn: !ImportValue OpsItemEventRoleArn
           InputTransformer:
             InputTemplate:
               Fn::Sub:
                   '{ "title": "CloudTrail CloudWatch Logs Compliance Failure",
                     "description": "CloudWatch Event Rule was triggered for Config Compliance Rule Failure.",
                     "source": "Config Compliance",
                     "priority": "2",
                     "severity": "1",
                     "notifications": [{ "arn": "arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:OpsCenterEventNotificationTopic"}],
                     "operationalData": {
                       "/aws/dedup": {"type": "SearchableString","value": "{\"dedupString\":\"SSMOpsItems-S3-Encrypted-enabled-failed\"}"}, 
                       "/aws/automations": { "value": "[ { \"automationType\": \"AWS:SSM:Automation\", \"automationId\": \"AWS-EnableS3BucketEncryption\" } ]" },
                       "/aws/resources": {"value": "[{\"arn\":\"arn:aws:s3:::<resourceId>\"}]","type": "SearchableString"},
                       "configRuleName": {"type": "SearchableString","value": <configRuleName>},
                       "resourceType": {"type": "SearchableString","value": <resourceType>},
                       "resourceId": {"type": "SearchableString","value": <resourceId>}
                     }
                   }'
             InputPathsMap:
               resourceType: "$.detail.resourceType"
               resourceId: "$.detail.resourceId"
               configRuleName: "$.detail.configRuleName"

