version: 0.1

phases:
  install:
    commands:
      - echo Installing rdk...
      - pip install .
      - pip install rdklib
  pre_build:
    commands:
      - echo Starting tests
      - rm -rf LP3*
  build:
    commands:
      - rdk create-region-set -o test-region
      - rdk -f test-region.yaml init
      - rdk create MFA_ENABLED_RULE --runtime python3.10 --resource-types AWS::IAM::User
      - rdk -f test-region.yaml deploy MFA_ENABLED_RULE
      - sleep 30
      - python3 testing/multi_region_execution_test.py
      - sleep 30
      - rdk -f test-region.yaml undeploy --force MFA_ENABLED_RULE
      - python3 testing/partition_test.py
      - rdk init --generate-lambda-layer
      - rdk create LP3_TestRule_P310_lib --runtime python3.10-lib --resource-types AWS::EC2::SecurityGroup
      - rdk create LP3_TestRule_P39_lib --runtime python3.9-lib --resource-types AWS::EC2::SecurityGroup
      - rdk create LP3_TestRule_P38_lib --runtime python3.8-lib --resource-types AWS::EC2::SecurityGroup
      - rdk create LP3_TestRule_P37_lib --runtime python3.7-lib --resource-types AWS::EC2::SecurityGroup
      - rdk -f test-region.yaml deploy LP3_TestRule_P310_lib --generated-lambda-layer
      - rdk -f test-region.yaml deploy LP3_TestRule_P39_lib --generated-lambda-layer
      - rdk -f test-region.yaml deploy LP3_TestRule_P38_lib --generated-lambda-layer
      - rdk -f test-region.yaml deploy LP3_TestRule_P37_lib --generated-lambda-layer
      - yes | rdk -f test-region.yaml undeploy LP3_TestRule_P310_lib
      - yes | rdk -f test-region.yaml undeploy LP3_TestRule_P39_lib
      - yes | rdk -f test-region.yaml undeploy LP3_TestRule_P38_lib
      - yes | rdk -f test-region.yaml undeploy LP3_TestRule_P37_lib
      - rdk create LP3_TestRule_P310 --runtime python3.10 --resource-types AWS::EC2::SecurityGroup
      - rdk create LP3_TestRule_P39 --runtime python3.9 --resource-types AWS::EC2::SecurityGroup
      - rdk create LP3_TestRule_P38 --runtime python3.8 --resource-types AWS::EC2::SecurityGroup
      - rdk create LP3_TestRule_P37 --runtime python3.7 --resource-types AWS::EC2::SecurityGroup
      - rdk create LP3_TestRule_P3 --runtime python3.10 --resource-types AWS::EC2::SecurityGroup
      - rdk create LP3_TestRule_EFSFS --runtime python3.10 --resource-types AWS::EFS::FileSystem
      - rdk create LP3_TestRule_ECSTD --runtime python3.10 --resource-types AWS::ECS::TaskDefinition
      - rdk create LP3_TestRule_ECSS --runtime python3.10 --resource-types AWS::ECS::Service
      - rdk modify LP3_TestRule_P3 --input-parameters '{"TestParameter":"TestValue"}'
      - rdk create LP3_TestRule_P37_Periodic --runtime python3.7 --maximum-frequency One_Hour
      - rdk create LP3_TestRule_P37lib_Periodic --runtime python3.7-lib --maximum-frequency One_Hour
      - rdk create LP3_TestRule_P38_Periodic --runtime python3.8 --maximum-frequency One_Hour
      - rdk create LP3_TestRule_P38lib_Periodic --runtime python3.8-lib --maximum-frequency One_Hour
      - rdk create LP3_TestRule_P39_Periodic --runtime python3.9 --maximum-frequency One_Hour
      - rdk create LP3_TestRule_P39lib_Periodic --runtime python3.9-lib --maximum-frequency One_Hour
      - rdk create LP3_TestRule_P310_Periodic --runtime python3.10 --maximum-frequency One_Hour
      - rdk create LP3_TestRule_P310lib_Periodic --runtime python3.10-lib --maximum-frequency One_Hour
      - rdk test-local --all
      - rdk deploy --all
      - yes | rdk undeploy LP3_TestRule_P3
      - yes | rdk undeploy LP3_TestRule_P37
      - yes | rdk undeploy LP3_TestRule_P37_Periodic
      - yes | rdk undeploy LP3_TestRule_P38
      - yes | rdk undeploy LP3_TestRule_P38_Periodic
      - yes | rdk undeploy LP3_TestRule_P39
      - yes | rdk undeploy LP3_TestRule_P39_Periodic
      - yes | rdk undeploy LP3_TestRule_P310
      - yes | rdk undeploy LP3_TestRule_P310_Periodic
      - sleep 30
      - rdk logs LP3_TestRule_P3
      - yes | rdk undeploy -a
  post_build:
    commands:
      - echo Build completed on `date`
