version: 0.1

phases:
  install:
    commands:
      - apt-get update -y
  build:
    commands:
      - echo Creating Windows build server and running tests
      - bash testing/test_windows.sh 2
  post_build:
    commands:
      - echo Build completed on `date`
