name: 'Validation'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    name: Run Security Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Dependencies
        uses: './.github/actions/dep-setup'
        with:
          python-version: '3.10'

      - name: Run Security Checks
        shell: bash
        run: poetry poe safety
